# Generated by Django 3.0.7 on 2021-03-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.CharField(max_length=30)),
                ('second_team', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
        ),
    ]
