# Generated by Django 3.0.7 on 2021-03-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_match_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
